target 'weatherApp' do
 	use_frameworks!

	pod 'SwiftyJSON', '~> 2.3'
  	pod 'Alamofire', '~> 3.4'
	pod 'AlamofireImage', '~> 2.4'

	target 'weatherAppTests' do
    	inherit! :search_paths
  	end
  	
	target 'weatherAppUITests' do
    	inherit! :search_paths
  	end

end
